// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBElCafzSSRFloLjlB-vGb5TBSET1pEKQU',
    appId: '1:459509276666:web:5106a2a0bcb6a493cbce43',
    messagingSenderId: '459509276666',
    projectId: 'taalmel-e0e35',
    authDomain: 'taalmel-e0e35.firebaseapp.com',
    storageBucket: 'taalmel-e0e35.firebasestorage.app',
    measurementId: 'G-514C0KV2J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTghjpLsfhaCbqdXFqSDXOj4limueicuU',
    appId: '1:459509276666:android:dfd8515e26af4c7acbce43',
    messagingSenderId: '459509276666',
    projectId: 'taalmel-e0e35',
    storageBucket: 'taalmel-e0e35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1rgSItpZZlhUzt-yCHX_RvlSQcIR4aJ8',
    appId: '1:459509276666:ios:b6da8c762f13e77dcbce43',
    messagingSenderId: '459509276666',
    projectId: 'taalmel-e0e35',
    storageBucket: 'taalmel-e0e35.firebasestorage.app',
    iosBundleId: 'com.example.taalmel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1rgSItpZZlhUzt-yCHX_RvlSQcIR4aJ8',
    appId: '1:459509276666:ios:b6da8c762f13e77dcbce43',
    messagingSenderId: '459509276666',
    projectId: 'taalmel-e0e35',
    storageBucket: 'taalmel-e0e35.firebasestorage.app',
    iosBundleId: 'com.example.taalmel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBElCafzSSRFloLjlB-vGb5TBSET1pEKQU',
    appId: '1:459509276666:web:bdc0ea0d06589fdecbce43',
    messagingSenderId: '459509276666',
    projectId: 'taalmel-e0e35',
    authDomain: 'taalmel-e0e35.firebaseapp.com',
    storageBucket: 'taalmel-e0e35.firebasestorage.app',
    measurementId: 'G-MF4H3V7HTX',
  );
}
